6/build website
stockpile-co/stockpileapp.co pull request #11
Opened 2017-06-10 02:47 UTC by AdamVig

Closes #6.

2017-06-10 03:02 UTC, AdamVig commented
*Note: Screenshots are for reference only! They are not a very good representation of the website.*
# Homepage
![image](https://user-images.githubusercontent.com/5354752/26999411-b40a7b74-4d66-11e7-8b73-2ac4a4c9985a.png)
![image](https://user-images.githubusercontent.com/5354752/26999433-6fbff6b4-4d67-11e7-845d-28e7a053310a.png)
![image](https://user-images.githubusercontent.com/5354752/26999439-88be2a00-4d67-11e7-9213-c7c71fc13b42.png)


# Subscribe Page
![image](https://user-images.githubusercontent.com/5354752/26999406-98884b42-4d66-11e7-8dda-dc165978fb32.png)

2017-06-10 18:20 UTC, emroussel requested changes
Great job!

I think in general I would add more space between every sections and between the header and the first section.

Also, I'm not sure if this was voluntary or not, but the website as a whole feels off centered. The sections in the middle are aligned to the right. There is also more space between the text and the image in the section for scanning than there is for the section about viewing inventory and kits.

Finally, I feel like screenshots would look better if they are placed inside a phone frame.

2017-06-10 18:20 UTC, emroussel commented on src/index.html
> +                    <div class="stockpile-inventory"></div>
Should this be `<div class="stockpile-scan"></div>` instead?

2017-06-10 18:20 UTC, emroussel commented on src/index.html
> +                        anything when you rent items.
I think reading through the different sections, the word 'item' is repeated a lot. Is there a way we can rephrase some of them to make it flow a little better?

2017-06-11 01:53 UTC, AdamVig commented
Awesome feedback, thanks! I realized as soon as I looked at it again that it needed a lot more work. Here are updated screenshots, which are actually accurate this time (I used an extension instead of hand-capturing them 😆).

### Laptop with HiDPI Screen
![image](https://user-images.githubusercontent.com/5354752/27007620-3106d184-4e27-11e7-8255-7944b8783354.png)

### iPad
![image](https://user-images.githubusercontent.com/5354752/27007622-39965630-4e27-11e7-8362-8936ebfeb5ea.png)

### iPhone 6
![image](https://user-images.githubusercontent.com/5354752/27007623-3dc6d680-4e27-11e7-9966-a2247090eb56.png)

2017-06-11 21:55 UTC, emroussel commented
Yes it looks much better, good job!

Two more things that I thought of when looking at it again:
- Maybe adding a title for each section would be helpful to indicate which image/screenshot is associated with what text on mobile (One or very few words describing what the section is about). The whitespace helps, but I still had a few moments of hesitation when I first saw it. It could be above the text or centered above both the image and text, not sure which would look better. Could be similar to [stripe.com](https://stripe.com/) if you think it fits for Stockpile.
- If you had titles for sections, it might make sense to have a navigation bar in the header that has links to these different sections.

Also, I just realized that we never mention that what we are selling is an app 😂

Might be worth adding that to the description or somewhere else. Another option might be to have the classic two images of iOS and Android with our app instead of where the logo is right now and move the logo to the navbar or something.

2017-06-12 01:27 UTC, AdamVig commented
### 1080p Screen
![image](https://user-images.githubusercontent.com/5354752/27016280-1ea096cc-4eec-11e7-8e5e-3bdcd8857951.png)

### iPhone 6
![image](https://user-images.githubusercontent.com/5354752/27016316-73dc0b94-4eec-11e7-8aba-683714a05096.png)

I decided to pass on adding section links to the nav bar. The page is so short and simple that I don't think section links would add any value. I will add links to the subscribe page and the barcodes page once they exist, but that will be in each of their pull requests, not this one.

I thought about how to add the word "app" in somewhere, but couldn't see any place where it fit naturally. I think the screenshots do a good enough job of getting the point across. We'll have to do some user testing of our website copy, though, to check if it actually communicates well.

2017-06-12 03:20 UTC, emroussel approved these changes

2017-06-12 03:21 UTC, emroussel commented
Sounds good, and I love the titles of sections!

2017-06-13 00:10 UTC, merged